version: '3.4'

services:

  provider:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8181:8181
    volumes:
      - shared-volume:/tmp/copy

  consumer:
    build:
      context: ..
      target: prs-connector-consumer
      args:
        BUILD_TARGET: prs-connector-consumer
    ports:
      - 9191:9191

  integration-test:
    image: adoptopenjdk:11-jre-hotspot
    command: >
      sh -c "curl -O https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
             chmod +x wait-for-it.sh  &&
             curl -O https://raw.githubusercontent.com/kadwanev/retry/master/retry &&
             chmod +x retry  &&
             ./wait-for-it.sh -t 60 provider:8181 &&
             ./wait-for-it.sh -t 60 consumer:9191 &&
             mkdir -p /tmp/copy/source /tmp/copy/dest &&
             echo value-in-test-document > /tmp/copy/source/test-document.txt &&
             curl -X POST 'http://consumer:9191/api/file/test-document?connectorAddress=http://provider:8181/&destination=/tmp/copy/dest/new-document.txt' > /tmp/copy/pid &&
             echo PID=`cat /tmp/copy/pid` &&
             # retry until status endpoint returns COMPLETED
             ./retry -t 15 'curl -X GET http://consumer:9191/api/datarequest/`cat /tmp/copy/pid`/state'"
    volumes:
      - shared-volume:/tmp/copy

volumes:
  shared-volume:
